### ISSUE TITLE
finish inside freeview?

### ISSUE THREAD

**Issue by MohsenShafiee** [jcmore2/FreeView#1]
hi
thanks for this nice library...
how to finish the freeview by a button click?
I mean I want to some buttons on freeview. is it possible?

**Comment by jcmore2** [comment]
Hi!

Of course you can create any button you want inside your freeview. You just need to inflate set click listener to this button and send the view to FreeView library.

```
    final View content = ((LayoutInflater)mActivity.getSystemService(Context.LAYOUT_INFLATER_SERVICE)).inflate(R.layout.content, null);

    content.findViewById(R.id.button).setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            FreeView.get().dismissFreeView();
        }
    });
```

FreeView.init(MainActivity.this).withView(content).showFreeView();
